<?php
namespace Admin\Model;

class ConstantModel extends CommonModel
{
    public function addOne($data)
    {
        $data['value'] = json_encode($data['value']);
        return parent::addOne($data); // TODO: Change the autogenerated stub
    }

    public function getByTag($tag){
        $where = ['tag' => $tag];
        $data = $this->where($where)->find();
        $data['value'] = json_decode($data['value'], true);
        return $data;
    }
}